version: '2'
services:
  search_pipeline:
    build: search-pipeline
    image: andreformento/search-pipeline:latest
    container_name: search_pipeline
    ports:
      - 8083:8083
    environment:
      SERVER_PORT: 8083
    networks:
      - development

networks:
  development:
